### ISSUE TITLE
converting polygons to GeometryBasics gives MethodError

### ISSUE THREAD

**Issue by tiemvanderdeure** [JuliaGeo/GeoInterface.jl#100] opened 2023-05-22 11:45 UTC
Hi!
I am calling GeoInterface.convert on a vector of polygons from a Shapefile, in order to plot them using Makie.

[Download link for the shapefile I am using](https://datacatalogfiles.worldbank.org/ddh-published/0038272/DR0046659/wb_countries_admin0_10m.zip?versionId=2023-01-19T09:29:21.5328649Z)

The code below used to work, but after updating to the latest release gives me;
`MethodError: no method matching ncoord(::LinearRingTrait, ::Shapefile.LinearRing{Shapefile.Point, Nothing, Nothing})`

```
using Shapefile, GeoInterface, GeometryBasics
countries = Shapefile.Table("WB_countries_Admin0_10m/WB_countries_Admin0_10m.shp");
basic_geoms = GeoInterface.convert.(Ref(GeometryBasics), Vector{Shapefile.Polygon}(countries.geometry));

```

**Comment by rafaqz** [comment] 2023-05-22 12:34
Yeah... someone just fixed something else that broke this.

The good news I already fixed it more generally here:

https://github.com/JuliaGeo/Shapefile.jl/pull/85

But I cant reproduce the CI error on my own machines, and no-one else has bothered running it on their machines, so we are at an impass.

You can probably just use that branch to solve your problem and firget about it (Thats what Im doing), but running `] test Shapefile` might give us some insight into what the failures are.

**Comment by felixcremer** [comment] 2023-06-30 03:12
This is fixed in Shapefile.jl.

**Closed by felixcremer** 2023-06-30 03:12 UTC
